### ISSUE TITLE
Making boxShadow customisable

### ISSUE THREAD

**Issue by WD-J** [karvulf/flutter-reorderable-grid-view#10]
Hi - great package you've made! Would greatly appreciate the ability to customise the boxShadow. I have circular items with a square shadow. Wanting to change the color is also another use-case.

**Comment by karvulf** [comment]
Hello @WD-J 
Thank you for your request.
I will implement this usecase for you this evening und publish it.

**Comment by WD-J** [comment]
Amazing response time. I greatly appreciate it. Thank you, @karvulf !

**Comment by karvulf** [comment]
I added a new parameter called `dragChildBoxDecoration`
The default value for the BoxDecoration is
```
BoxDecoration(
    boxShadow: <BoxShadow>[
      BoxShadow(
        color: Colors.black.withOpacity(0.2),
        spreadRadius: 5,
        blurRadius: 6,
        offset: const Offset(0, 3), // changes position of shadow
      ),
    ],
  );
```

You can override that with your preferred BoxDecoration, just add the shape `BoxShape.circle`, your color and update the shadow if you want. :)

You can get the update with Version `1.1.3`. @WD-J

**Comment by WD-J** [comment]
Amazing. Thank you so much!
