### ISSUE TITLE
can it close the animation? it sharks my eyes

### ISSUE THREAD

**Issue by linuxdrake** [karvulf/flutter-reorderable-grid-view#102]
can it close the animation? it shark my eyes,thks

**Comment by linuxdrake** [comment]
when i open the page, it always operate the animation. I just hope it does when dragging

**Comment by karvulf** [comment]
Hallo @linuxdrake 
Can you give me more details?
So you wish to disable the whole animations or specific ones? And does the animation not work for dragging or how is your last sentence meant?

**Comment by linuxdrake** [comment]
the animation for dragging is ok for me. if I adjust the order of widgets of gridview, click other bottombar and return to the current page, there is always the animation from original order to the last new order, i don't want this animation.

**Comment by karvulf** [comment]
This sounds a bit like the whole widget is rebuilt. Can you show me this behavior in a video and provide the code you have?  @linuxdrake

**Comment by linuxdrake** [comment]
![eed65c09be80eb2db150a99fb4f8f48e](https://github.com/karvulf/flutter-reorderable-grid-view/assets/19860478/c262b909-77e2-49a8-a12b-239bb919b59e)
 from other tab to current page, there is a little animation. I wish the order is quit,thks

**Comment by linuxdrake** [comment]
![eed65c09be80eb2db150a99fb4f8f48e](https://github.com/karvulf/flutter-reorderable-grid-view/assets/19860478/0c7ac500-9a1f-4ddf-9a9b-8c44b8e1a462)

**Comment by karvulf** [comment]
Which version do you use? 
This animation only happens every time because the widget is rebuilt.
If you use the version `5.0.0-dev.10`, you could set `fadeInDuration` to `Duration.zero` to have no animation. @linuxdrake

**Comment by linuxdrake** [comment]
yes, I used the version 5.0.0-dev.10,but appears an error:"The argument type 'void Function(List<ReorderUpdateEntity>)' can't be assigned to the parameter type 'void Function(List<dynamic>".
![image](https://github.com/karvulf/flutter-reorderable-grid-view/assets/19860478/f95a81c4-c189-487a-91ef-6d86b55d2cd4)

**Comment by linuxdrake** [comment]
> yes, I used the version 5.0.0-dev.10,but appears an error:"The argument type 'void Function(List)' can't be assigned to the parameter type 'void Function(List)". ![image](https://private-user-images.githubusercontent.com/19860478/312494148-f95a81c4-c189-487a-91ef-6d86b55d2cd4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAzNDAyNDgsIm5iZiI6MTcxMDMzOTk0OCwicGF0aCI6Ii8xOTg2MDQ3OC8zMTI0OTQxNDgtZjk1YTgxYzQtYzE4OS00ODdhLTkxZWYtNmQ4NmI1NWQyY2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzEzVDE0MjU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxODg4ODFhN2ZjNzNiNmMyYWNhYjQzMmQ3NmM0NTYyNDFjMTg4ZjViYTFiMzk1OTY4ZjZmNjdkY2UzOTNkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SlH91dECIMl-uu1_Er9izWNeIPTFgAZUhI9tCo-YPLo) what's wrong with it?

**Comment by karvulf** [comment]
this part has changed with the version, so if you use the `onReorder`, you should use it like this: @linuxdrake 
```dart
... 
onReorder: (reorderedListFunction) {
    setState(() {
      myBooks = reorderedListFunction(myBooks) as List<YOUR_BOOK_TYPE>;
    });
}
...
```

**Comment by linuxdrake** [comment]
sorry, the code can run ,but the animation stll appers.

**Comment by linuxdrake** [comment]
I found if i removed the inistate ,the animation is gone. it would avoid the inistate, does't it?
I would put the initial work at other place.

**Comment by linuxdrake** [comment]
@karvulf  thank you very much. it worked after i removed the initiation in the inistate function.
