### ISSUE TITLE
Issue: Lags with `ReorderableBuilder.builder`

### ISSUE THREAD

**Issue by karvulf** [karvulf/flutter-reorderable-grid-view#107]
This issue is created because of #43 where there were problems using `ReorderableBuilder.builder` and scrolling through the items.
After a couple of time, there were lags.

A suggestion was to remove `setState` for `_handleMovingFinished` and `_handleOpacityFinished` in  `ReorderableBuilder` which causes a rebuilt for all children. But to ensure these children are correctly updating themself, somehow these widgets have to listen to changes of `ReorderableEntity`.

**Comment by abdelaziz-mahdy** [comment]
I hope you're doing well. I wanted to check if there have been any updates on this. I understand if you're busy, but I would appreciate knowing if it's possible.

**Comment by karvulf** [comment]
Hello @abdelaziz-mahdy 
I will try to find some time this weekend to see if I can find an improvement

**Comment by abdelaziz-mahdy** [comment]
Thank you ❤️

**Comment by karvulf** [comment]
Good morning @abdelaziz-mahdy 
I wanted to ask if you still have these issues with the newest flutter version `3.24.2`?
I tested it with `Reorderable.builder` on iPhone 15 and Galaxy Flip 3 and I didn't get any lags or not appearing images while scrolling. Every child got an image in this test.
I will try to find a solution for the `setState` after the opacity finished anyway but probably flutter also improved the performance.

**Comment by abdelaziz-mahdy** [comment]
> Good morning @abdelaziz-mahdy 
> I wanted to ask if you still have these issues with the newest flutter version `3.24.2`?
> I tested it with `Reorderable.builder` on iPhone 15 and Galaxy Flip 3 and I didn't get any lags or not appearing images while scrolling. Every child got an image in this test.
> I will try to find a solution for the `setState` after the opacity finished anyway but probably flutter also improved the performance.

Yeah flutter improved the performance but due to me rendering a list of images in which there is animation it takes time to build so I get a stutter, I am trying to optimize my list but any render reduction will be awesome

**Comment by karvulf** [comment]
I have made some changes which definitely improves the performance to 10 or more frames.
Can you try if version `5.1.0-dev.1 ` is working better for you? @abdelaziz-mahdy

**Comment by abdelaziz-mahdy** [comment]
> I have made some changes which definitely improves the performance to 10 or more frames.
> Can you try if version `5.1.0-dev.1 ` is working better for you? @abdelaziz-mahdy 

Oh okay will try that and let you know, thank you

**Comment by abdelaziz-mahdy** [comment]
nice i see no more full widget rerender on scrolling so all good in that version, thats awesome thank you <3

**Comment by karvulf** [comment]
That's good to know, thank you for the link. :)
I just published version `5.1.0` which contains the improvement. If there is something else not working like expected, you can open another issue. Thank you for your support!

**Comment by abdelaziz-mahdy** [comment]
thank you for the awesome package and your help <3
