### ISSUE TITLE
Can't drag/drop in flutter web

### ISSUE THREAD

**Issue by loic-hamdi** [karvulf/flutter-reorderable-grid-view#115]
Using the [example](https://github.com/karvulf/flutter-reorderable-grid-view/blob/master/example/lib/main.dar) I cannot drag/drop the `GridView` children on flutter web.

The children switch animation works when I trigger manually with 

```dart
setState(() {
  final child = children.removeAt(0);
  children.insert(1, child);
});
```

Any idea what could cause this behavior?

**Comment by karvulf** [comment]
Hi @loic-hamdi 
it seems like you solved the issue. If anything wasn't clear, please let me know it.
