### ISSUE TITLE
[Request] Add a feature where there can be a header and/or footer that is not draggable, and not reorderable.

### ISSUE THREAD

**Issue by isenbj** [karvulf/flutter-reorderable-grid-view#124]
I love you package but the only thing keeping me from using it right now is the missing feature to add an immovable footer like the below library. 

https://pub.dev/packages/reorderable_grid_view

**Comment by karvulf** [comment]
Hallo @isenbj 
Do you mean the plus card on the gif? @isenbj

**Comment by isenbj** [comment]
@karvulf yes.

**Comment by karvulf** [comment]
That's possible. @isenbj 
You can add `lockedIndices` and define which children are not movable and draggable.
E.g. if you want to have the first item locked, you specifiy the following:

```dart
...
lockedIndices: <int>[0],
...
```

**Comment by isenbj** [comment]
Okay that works, though it is unfortunate I have to add a dummy data to the list for this though, as that library has a footer input option.

**Comment by karvulf** [comment]
Ah I see thanks for the feedback 
Like this I can ensure that the GridView builds as expected, implementing the other solution it could lead into rendering issues but not sure though @isenbj
