### ISSUE TITLE
Add support for ReorderableGridView.builder()

### ISSUE THREAD

**Issue by renannery** [karvulf/flutter-reorderable-grid-view#13]
When dealing with a large list, it can get pretty slow while scrolling.

I understand the implementation is different and quite challenging, but something to consider support for better performance.

**Comment by RobinNerg** [comment]
Hello @renannery 

Thank you for your feedback.
I will definitely take a look to improve that, I have some ideas.

**Comment by karvulf** [comment]
Hello @renannery 

Thank you for your feedback.
I will take a look to improve the performance. I have some ideas.

**Comment by karvulf** [comment]
I released a new release candidate for the version 2.0.0.
I added the implementations for all types of GridViews, including `GridView.builder`. This also improve the performance generally.

If you want to try that, you can use the version `2.0.0-dev.1`.

@renannery

**Comment by renannery** [comment]
Thank you! I've just tested and apparently, the animation stopped working when items are moving position in the gridview.
In my implementation, there is no user interaction with drag-and-drop, the elements change their positions randomly according to our API and until version 1.1.5 it works just fine.

Switching to `2.0.0-dev.1` using the default constructor `ReorderableGridView()` the animation won't work

**Comment by karvulf** [comment]
Ah ok, this implementation is still in process.
Currently I only have rebuilt the drag and drop functionality.
The animation type is a bit more difficult, but if I am successfull, there will be another widget, that you can only use for that type of animation, sth like `AnimatedReorderableGridView` or both of them combined.
@renannery

**Comment by karvulf** [comment]
There is a new update for the release candidate.
I added the missing animation for all types in the GridView. For `ReorderableWrap` it is currently not supported.

You can test`2.0.0-dev.2`. There you also should have a better performance when using `ReorderableGridView.builder`.
@renannery

**Comment by karvulf** [comment]
Hello @renannery 
Today, I released the official version `2.0.0`.
Now you have also support for `GridView.builder`. Check out the example too see more about that.
