### ISSUE TITLE
5.3.1 breaks reordering

### ISSUE THREAD

**Issue by isenbj** [karvulf/flutter-reorderable-grid-view#137]
See video. This is a list of reorderable grid views in the first page of a PageView.builder. It worked perfectly fine before. Seems that scrolling down some breaks things.

https://youtu.be/AmYe9iK18G8

**Comment by karvulf** [comment]
Hi @isenbj 
Unfortunately I cannot see the video. Is it the same code you showed the last time? 
I am also fixing an issue which was found here #135 , maybe it’s related

**Comment by isenbj** [comment]
The video seems to have gotten stuck. Try this one.

https://youtu.be/dSKMva2Gj0U

The other issue I mentioned I have not been able to break it down to be reproducible yet.

**Comment by karvulf** [comment]
Interesting, did you add a ScrollController to `ReorderableBuilder`? @isenbj

**Comment by isenbj** [comment]
Ahh, yes I did! Before I think it was needed so that I could drag down to other ReorderableBuilders and drop. But not it seems removing the ScrollController still works, and I am still able to drag down to other reorderables.

**Comment by isenbj** [comment]
Fantastic work by the way. As you can see in my app, it is a very nice addition.

**Comment by karvulf** [comment]
I created an issue to improve this behavior because it's a bit confusing currently.
Your app looks really great, I am happy to see that it's working for you so well :) @isenbj
