### ISSUE TITLE
ReorderableBuilder does not support generics, resulting in dynamic type in the onReorder function

### ISSUE THREAD

**Issue by KevenMelo** [karvulf/flutter-reorderable-grid-view#142]
Currently, the ReorderableBuilder in the flutter_reorderable_grid_view package does not support generics. This causes the onReorder function to have a dynamic type, which can lead to type issues and lack of type safety in Dart.

Adding support for generics in ReorderableBuilder would improve type safety and the development experience.

**Comment by karvulf** [comment]
Hello @KevenMelo 
thanks for opening the issue. You are right, it’s not the best way how the function is currently used because of this dynamic type. As mentioned in the PR you opened, I will check it, thanks again.

**Comment by karvulf** [comment]
I merged your PR and will release it with version `3.4.0`. @KevenMelo

**Comment by karvulf** [comment]
Ok, it was a small thing but I found it and now it works :) @KevenMelo 
I just had to change the line:
```dart
  State<ReorderableBuilder> createState() => _ReorderableBuilderState();
```
to
```dart
  State<ReorderableBuilder<T>> createState() => _ReorderableBuilderState();
```
