### ISSUE TITLE
On reordering tiles index item at last place

### ISSUE THREAD

**Issue by govindmaheshwari2** [karvulf/flutter-reorderable-grid-view#35]
I have a list of items but when I reorder index to 0 and pass it to grid view then if more than 10 items are present(one page contain 4 item max). the reordered tile came to last even its index is 0.

**Comment by karvulf** [comment]
Hi @govindmaheshwari2 
Could you provide some code that you used? That would help to understand what you are trying to do.

**Comment by karvulf** [comment]
Closing this issue because I got no response.
If you are still having this issue, feel free to reopen it @govindmaheshwari2
