### ISSUE TITLE
Flutter 3.0.0 is detecting issue with the library

### ISSUE THREAD

**Issue by RoyalCoder88** [karvulf/flutter-reorderable-grid-view#37]
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_reorderable_grid_view-2.1.0/lib/widgets/animated/reorderable_draggable.dart:184:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {
                     ^
../../../Documents/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_reorderable_grid_view-2.1.0/lib/widgets/animated/reorderable_draggable.dart:208:22: Warning: Operand of null-aware operation '?.' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../../Documents/flutter/packages/flutter/lib/src/widgets/binding.dart').
      WidgetsBinding.instance?.addPostFrameCallback((_) {

P.S: Also updated the [flutter-reorderable-grid-view](https://github.com/karvulf/flutter-reorderable-grid-view) to v3.0
now I get these errors:
![errors](https://user-images.githubusercontent.com/6507433/168420492-3d100118-f814-4415-89f1-6119384a11ab.png)

**Comment by karvulf** [comment]
Hi @RoyalCoder88 
I will make an update for the flutter upgrade.

The other issue is coming from breaking changes with version 3.0.0 of my package.
Now you have to add the `ScrollController` by yourself and a key to `GridView`. You can see more on the example.

**Comment by karvulf** [comment]
I made an update `3.0.1` that should resolve the warnings.

Could you solve the other problem because of this package update @RoyalCoder88 ?

**Comment by RoyalCoder88** [comment]
@karvulf hi thanks, now everything it's perfect! 
Have a great day and keep up the good job!
