### ISSUE TITLE
Support reordering with animation for programatic changes to the data source

### ISSUE THREAD

**Issue by aytunch** [karvulf/flutter-reorderable-grid-view#5]
In my app, I don't need the user to reorder the contents but they are done when some filters are enabled.

Use case:

- Grids show cars.
- When user presses red color, I want to show only the red colored cars
- And I want this filtering to happen in an animated way.
- So there might be several cars that are removed from different places of the cars array.
- When the filter is removed, all cars should be added in place with ordering animation.

Can I use this package for this need?

[This implicitly_animated_reorderable_list package does it using a diff algorithm](https://github.com/bxqm/implicitly_animated_reorderable_list)

**Comment by RobinNerg** [comment]
Hello @aytunch 

Thank you for your reply. Currently this functionality is not supported. 
In general, if the size of children changes, there is no animation in the GridView or Wrap that I use.

But I like the idea that you have. I will try to implement a solution for this kind of feature.

**Comment by karvulf** [comment]
Hello @aytunch 

Thank you for your reply. Currently this functionality is not supported. 
In general, if the size of children changes, there is no animation in the GridView or Wrap that I use.

But I like the idea that you have. I will try to implement a solution for this kind of feature.

**Comment by aytunch** [comment]
Thanks for the quick reply, please share here if you get to work on it.
And I could help as much as possible if needed :)

**Comment by karvulf** [comment]
I have some updates about your request @aytunch.
I created a new branch called `feature/children-size-change-with-animation-v2`.

There are still some tests that I have to add and to fix and also some points in my code that needs a refactoring, but if you are interested, you can check out this branch with the following code in your `pubspec.yaml`:

```
  flutter_reorderable_grid_view:
    git:
      url: https://github.com/karvulf/flutter-reorderable-grid-view.git
      ref: feature/children-size-change-with-animation-v2
```

**Comment by karvulf** [comment]
I have merged the branch and I hope it works as expected. @aytunch 
Check out version `1.1.0` to test the new feature.
Be sure to add a unique key for every child and also you have to update your list when `onReorder` is called.

**Comment by naderhezzy** [comment]
Hello, and thanks for the great package.
My question: Is it possible to control the item-removal's animation speed?

- The animation for the removed item with an animated opacity
- The animations on all items that change their position because of the removed item

Thank you in advance.

**Comment by karvulf** [comment]
Hello @naderhezzy that should be possible. Can you open a new issue describing this? I will try to add this parameter on the weekend

**Comment by naderhezzy** [comment]
Thank you for your response. I opened the issue as requested.
