### ISSUE TITLE
The project is missing this file: change_children_bar.dart

### ISSUE THREAD

**Issue by maq10** [karvulf/flutter-reorderable-grid-view#50]
Your code is missing this file: change_children_bar.dart

**Comment by karvulf** [comment]
Hi @maq10 
How did you open the project and did you use the command `flutter pub get` on the example app? Because I don't see a problem finding the widget.

**Comment by karvulf** [comment]
Closing this issue because of no answer. If you are still facing this problem, you can reopen this issue :) @maq10
