### ISSUE TITLE
Cannot scroll horizontal correctly

### ISSUE THREAD

**Issue by HuyNguyen1590** [karvulf/flutter-reorderable-grid-view#53]
Please provide an option to support  "Scroll while dragging" for horizontal gridview

**Comment by HuyNguyen1590** [comment]
Thanks for your reply. I tried a lot of package but this is package i like most. Hope to see version 4.0.0 soon

**Comment by karvulf** [comment]
I will try to release it in the end of this year @HuyNguyen1590

**Comment by JDongKhan** [comment]
any progress?

**Comment by karvulf** [comment]
Hi,
I have some news. I started implementing this feature for the next major version. Currently the drag and drop is now possible. But you can't scroll while dragging an item. This is still buggy. I will try to fix that and will update the version `5.0.0-dev.3` where you could test that feature @JDongKhan

**Comment by karvulf** [comment]
I released version `5.0.0-dev.3` that supports also horizontal scrolling. There could be still some bugs, so let me know if something doesn't work @JDongKhan

**Comment by karvulf** [comment]
Released and supported with version 5.0.0
