### ISSUE TITLE
Cannot change crossAxisCount dynamically

### ISSUE THREAD

**Issue by Erfa** [karvulf/flutter-reorderable-grid-view#54]
I'm trying to build a reorderable grid view where the user can select the crossAxisCount value themselves. This causes a few problems. If I change crossAxisCount from 2 to 3, the item being dragged is is still of larger size from the previous value. The other items also don't move as you would expect.

Is this a known issue? I can probably get a minimal working example, but it should be trivial to reproduce.

**Comment by karvulf** [comment]
Hello @Erfa 
thank you for opening the issue. This issue is new to me but I think I know why this happens. Is it urgent to fix that issue for you? If not, I would add a fix for that problem for the next major release.

**Comment by Erfa** [comment]
Thanks for the quick reply @karvulf ! No worries, I'd be happy to get a fix at all. Feel free to place it in whatever version makes sense to you! It's a great package, I really think Flutter should have this built in.

**Comment by karvulf** [comment]
The next major release still needs some time, so you have to wait at least until the end of this year. But if you need this fix in the next days/weeks, I could try to fix that issue also for this version because in my next update I completely recoded the package. @Erfa

**Comment by Erfa** [comment]
I see! Well it would be convenient to get it earlier, so if the fix is easy I'd appreciate getting it in this version as well. But if it's tricky to get it into the old code no worries, I can work around it until the major version is released.

**Comment by karvulf** [comment]
Hi @Erfa 
Just to notify you that I didn’t forget you, I will take a further look today into your issue to estimate if I can make a fix for the current version :)

**Comment by karvulf** [comment]
So I investigated your issue and I think I have found a solution that should work well.
The main issue for this package is, that it has no control about the used GridView. So e. g. if you change the `crossAxisCount`, I wouldn't know that the position of the children have changed because of that.
In this case, you have to update the `GlobalKey` used for the `GridView` (`_gridViewKey = GlobalKey();`).
Then all positions will be recalculated but that also means that all widgets are rebuilt. I don't know if that is a problem for you. Did that solve your issue? @Erfa

**Comment by Erfa** [comment]
Yes, it seems to work, thank you @karvulf ! Although, setting a new GlobalKey only on the GridView still makes the tiles that automatically move around the one I drag to still move as if the tile size was the old one. If I also give a GlobalKey to ReorderableBuilder and update that, it fully works though. I'll go with that for now!

**Comment by karvulf** [comment]
Ah I understand, that's a difficult usecase. I will consider that for the next major update, thank you!
I am closing this issue as solved. @Erfa
