### ISSUE TITLE
Click on an item in the list

### ISSUE THREAD

**Issue by NathanFlorins** [karvulf/flutter-reorderable-grid-view#66]
Hello, can we click on an item in the list to be able to display it or execute something else, because I don't see any onTap method or others

**Comment by NathanFlorins** [comment]
If I use a Gridview.builder, I can't drag and drop

**Comment by NathanFlorins** [comment]
I found a solution

**Comment by karvulf** [comment]
Hello @NathanFlorins 
I am not sure what you exactly mean with your first question. Did you try to start a drag and drop which didn't start or was it something else?
If you want to use `GridView.builder` I recommend to use the version `5.0.0-dev.2` but it's still in progress, so there might be some bugs. The previous version doesn't really support GridView.builder. So if you want to use it for a good performance, you will need the version `5.0.0-dev.2`

**Comment by karvulf** [comment]
What do you mean by "display"? What is exactly your usecase? @NathanFlorins

**Comment by NathanFlorins** [comment]
`final generatedChildren = List.generate(fruits.length, (index) {
      return InkWell(
        key: Key(fruits.elementAt(index)),
        child: Container(
          decoration: const BoxDecoration(
              image: DecorationImage(
                  image: NetworkImage("https://source.unsplash.com/radom"),
                  fit: BoxFit.cover
              )
          ),
          child: Text(
            fruits.elementAt(index),
            style: const TextStyle(color: Colors.white),
          ),
        ),
      );
    });`

**Comment by NathanFlorins** [comment]
When i click on item, i whant to print the index of this item

**Comment by NathanFlorins** [comment]
`final generatedChildren = List.generate(fruits.length, (index) {
      return InkWell(
        key: Key(fruits.elementAt(index)),
        child: Container(
          decoration: const BoxDecoration(
              image: DecorationImage(
                  image: NetworkImage("https://source.unsplash.com/radom"),
                  fit: BoxFit.cover
              )
          ),
          child: Text(
            fruits.elementAt(index),
            style: const TextStyle(color: Colors.white),
          ),
        ),
      );
    });`

**Comment by NathanFlorins** [comment]
Its ok, I had to re-launch my editor. I do this

``final generatedChildren = List.generate(fruits.length, (index) {
      return InkWell(
        onTap: () => {
          print("Item $index")
        },
        key: Key(fruits.elementAt(index)),
        child: Container(
          decoration: const BoxDecoration(
              image: DecorationImage(
                  image: NetworkImage("https://source.unsplash.com/radom"),
                  fit: BoxFit.cover
              )
          ),
          child: Text(
            fruits.elementAt(index),
            style: const TextStyle(color: Colors.white),
          ),
        ),
      );
    });

**Comment by karvulf** [comment]
Ah ok, so it works now? :D @NathanFlorins

**Comment by karvulf** [comment]
Closing this issue, if something is still wrong, you can open a new issue @NathanFlorins
