### ISSUE TITLE
[bug] Animation while scrolling unintentional behavior (5.0.0)

### ISSUE THREAD

**Issue by isenbj** [karvulf/flutter-reorderable-grid-view#80]
See shared video for behavior.
* Fade Animation is glitchy while scrolling.
* Fade animation no longer works after dragging and dropping an item (shown at end of video)

This was done on the current head of 5.0.0 (8faf2ffbccd91f92e6ad9cbd045ac5c4e3164cfc) and is unchanged.

https://github.com/karvulf/flutter-reorderable-grid-view/assets/49786150/06cd83ba-d527-4225-8f22-f4cddc7c24c7

**Comment by karvulf** [comment]
What do you mean by `glitchy`?
The second thing I have to check it @isenbj

**Comment by isenbj** [comment]
At 3 seconds in the video, and at 7 seconds in the video you can see the animation is not right. 

And throughout the video you can see that the fade in/fade out is not always there. 

Expected behavior: the fade in/fade out should always happens when scrolling up or down.

**Comment by karvulf** [comment]
Yep you are right, that is something I have to improve, unfortunately it's not that easy. 
That's why I have to focus on that issue later. But thanks for noticing it @isenbj

**Comment by karvulf** [comment]
I am closing this one because I didn't got this issue anymore. If it's happening again, you can reopen this issue @isenbj :)
