### ISSUE TITLE
Animation duration for item removal and addition

### ISSUE THREAD

**Issue by naderhezzy** [karvulf/flutter-reorderable-grid-view#94]
Hello, and thanks for the great package.
My question: Is it possible to control the item-removal's animation speed?

The animation duration for the removed item with an animated opacity
The animation duration on all items that change their position because of the removed item

Thank you in advance.

**Comment by karvulf** [comment]
Thank you for opening, I totally forgot this request, I hope I can do that this week @naderhezzy

**Comment by naderhezzy** [comment]
> 

We hope that too and we will be waiting for it, just tell me if you need any help.

**Comment by karvulf** [comment]
Hello @naderhezzy 
I have some news for you, I added a duration for the position update. Unfortunately I cannot add a duration for removed items because currently it is not supported to animate this. I got some issues using a widget that is already removed, so I have to overthink how I could solve this. But I will do this once I finished the release 5.0.0. I hope that's ok for you

**Comment by karvulf** [comment]
I will release the version `v5.0.0-dev.9` that will contain a new parameter `positionDuration` that you can use to change the duration of the position updates.
I opened a new issue for the other duration -> #96

**Comment by naderhezzy** [comment]
Hello @karvulf 
are you planning to release the new version any sooner?
thank you

**Comment by karvulf** [comment]
Hello @naderhezzy 

I released one version that contains the duration for the addition of items, only the removal will be a bit more tricky and will take longer before I can release that part.

**Comment by naderhezzy** [comment]
Awesome! 
Can you please mention the exact version so we can ensure our pubspec.yaml is pointing to the right one?
(In the package's changelog the latest version declared is 4.0.0 which was released 8 months ago)

We appreciate your help and your great job.

**Comment by karvulf** [comment]
Change it to the following @naderhezzy 

```yaml
...
  flutter_reorderable_grid_view: ^5.0.0-dev.10
...
```

Be careful because this version contains some breaking changes. You can check them in the example app how to implement all of this: https://github.com/karvulf/flutter-reorderable-grid-view/blob/release/v5.0.0/example/lib/main.dart
